--liquibase formatted sql
--changeset bpiw:10
CREATE TABLE CART (
  ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  CREATED DATETIME NOT NULL
);

CREATE TABLE CART_ITEM(
    ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    PRODUCT_ID BIGINT NOT NULL,
    QUANTITY INT,
    CART_ID BIGINT NOT NULL,
    CONSTRAINT FK_CART_ITEM_PRODUCTS FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(ID),
    CONSTRAINT FK_CART_ITEM_CART_ID FOREIGN KEY (CART_ID) REFERENCES CART(ID)
);