--liquibase formatted sql
--changeset bpiw:21
ALTER TABLE `ORDER` ADD USER_ID BIGINT;
--changeset bpiw:22
ALTER TABLE `ORDER` ADD CONSTRAINT FK_ORDER_USER_ID FOREIGN KEY (USER_ID) REFERENCES USERS(ID);