--liquibase formatted sql
--changeset bpiw:1

CREATE TABLE PRODUCTS(
    PRODUCT_ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    CATEGORY VARCHAR(255) NOT NULL,
    DESCRIPTION TEXT NOT NULL,
    PRICE DECIMAL(9,2) NOT NULL,
    CURRENCY VARCHAR(3) NOT NULL
);

