--liquibase formatted sql
--changeset bpiw:5
CREATE TABLE CATEGORIES (
    CATEGORY_ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION TEXT,
    SLUG VARCHAR(255) NOT NULL
);