--liquibase formatted sql
--changeset bpiw:6
ALTER TABLE PRODUCTS ADD CATEGORY_ID BIGINT AFTER CATEGORY;
ALTER TABLE PRODUCTS DROP COLUMN CATEGORY;
ALTER TABLE PRODUCTS ADD CONSTRAINT FK_PRODUCTS_CATEGORY_ID FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIES(CATEGORY_ID);