--liquibase formatted sql
--changeset bpiw:7
INSERT INTO CATEGORY (ID,NAME,DESCRIPTION,SLUG) VALUES (1,'inne','','inne');
UPDATE PRODUCT SET CATEGORY_ID=1;
ALTER TABLE PRODUCT MODIFY CATEGORY_ID BIGINT NOT NULL;