--liquibase formatted sql
--changeset bpiw:7
INSERT INTO CATEGORIES (CATEGORY_ID,NAME,DESCRIPTION,SLUG) VALUES (1,'inne','','inne');
UPDATE PRODUCTS SET CATEGORY_ID=1;
ALTER TABLE PRODUCTS MODIFY CATEGORY_ID BIGINT NOT NULL;